// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt_9Nx3EgaJSKoSxuAKwiEtlzdZQtTGfE',
    appId: '1:25939813746:android:bbda8d96c361ae7ea2a9eb',
    messagingSenderId: '25939813746',
    projectId: 'ezitech-c2c75',
    databaseURL: 'https://ezitech-c2c75-default-rtdb.firebaseio.com',
    storageBucket: 'ezitech-c2c75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdePbT3AOi5tpf5S1xcsoILcxXEtxX5N4',
    appId: '1:25939813746:ios:fbd611add7e4c8a8a2a9eb',
    messagingSenderId: '25939813746',
    projectId: 'ezitech-c2c75',
    databaseURL: 'https://ezitech-c2c75-default-rtdb.firebaseio.com',
    storageBucket: 'ezitech-c2c75.appspot.com',
    androidClientId: '25939813746-iqe78gjupmdkb7dbdgrauh0piljqj3v6.apps.googleusercontent.com',
    iosClientId: '25939813746-i4c2h2kb8lug9vkf73bsdgmapt6vbppe.apps.googleusercontent.com',
    iosBundleId: 'com.example.bestUiDesign',
  );
}
